apiVersion: v1
kind: Secret
metadata:
  name: remote-signer
  namespace: default
data:
  key_0551F452ABE463A4: LS0tLS1CRUdJTiBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQoKbFFXR0JGODY2dlFCREFERlMweFRiVnpFZ3ZHaTZaa2xXeHVOSGRPNmFqdG9kbm82WGd0bkFYNzRsSEN1WVRVawpLWDFFNkFBU2RYT1ZydzRRUVY4TVVJMktGczZyNlVoeEtjUnB3M003U0dlSVlreXQ1dVdqWkJZUUZuQ3UzVjhWCmZPQWRYcWJQcGxsaVpoZkgyVWJET2FXQzk3SjQvOGtPVzhpQW1GRUwzRHB2WUY3Ti93Rng5VmtSNlQ4cW5PaFYKaktzT215aDhDY3hTUTBwb3hLdEljQ3BBZnBUZEcyZkkybWF1eDcxa0k4QjNGZHUvZmMvM0d2VHZ5MzdnaXo5SQo5R0hHRXpicldFMkZvWmVGNGNVSkM5WmlZNi96bVBjVFVJaGU3SEdqS2NFanlaK3RxUTNjdkoxbFZLWHZob0pwCjArbmhZNG52RlZRZTBqTm9kL2R1SlZER3hWQlBEbVFJUHZENUZaQXRRVWdYMHhiNVRkNHMvdml3LzdNNVhqRVQKV1ZlZzZtdnhuNlhhajZvbzRrUWlERiswMHVPZnFCbGpYeGx4Rk12SDJOUG5teDlIN1haNy9NWFdsK1lvdFVmVAp6VzBWZXpwRThCOWdrelpWaXI4NGljYjVPZjM4REVxVW92akpWR3c5cEVXZCtpbnRXZUVLRHVYdCtpdjNqWGJQCjMxaExxTUZTcjRROS9VOEFFUUVBQWY0SEF3THc1dDA2SnZ3MmZmK0g5NERjZ1JrdVpBSE9PZ0xVM05oMGlyS1IKUmdMM1JpdHBXMGNMRjNsUHNxQ3R4NGkyV0xPL3FEVEhwcmNXMU9lL1h0SHhDT2czM2kxandCOHVNc1V3QndlcwppNEhSUDBBWkpYYngvVUVCenFCaElHSWxqRVhyU2ZyS1podjNLZFpDZHE3S3lpTmkrTnE0NGxrMi9NUHZwVGFKCmxMWUZzc3JyV3BlWGhyNjJBWHJqVUl0anRlODk1RzRXUTc3bnlIYWdhTEc3YXcrR2cyeDlDdG9ISDNIN3c3RG4KdU9IWjVwM2JDMXJoWmZXQjJkckpDbTRiYm93NCtBNjlJZDhkU2ZVTlNhR0JkUS9MZEpCeVQ1dUxRQS9ROTQ3bApEV0hpMkFUejBoV2FjY25oWGcycU55UmQwOGxVSHhab1BOeXZhakhNL2VnQnFXc0RRVkFqU1FXMzdnbTA2bmNNCkZ5SnZyREpkRTRIaFo5UzN3dS90bFM1L0V4SDZuREdCQVQ5SFpabXlSeDYvRmVMWFFHc1VTYklXbWkrRTJZYlcKWGNIQlN6YW44ZG5Pa0N5YTlQZDdSejlLeGROWGhKTWFTalVLbFB2WmZwMm9FcE1BUVkxbVNJM1RaUExYV1B0VgpONkVuQ3ZVTjJVcHIrRW1sbGYxYVFjRCtOSnliQi93cUhsZ3lkWVdVUkZVZ29EcnNjM1liQks3bVdaVmJ1OGx3CmJIdlNXWm5FZnYzaDN5TFJPcVlJbG83eW4wQlQxOFU2MDNlRlUrbXo0bXFmc1ZzalhOQXJKTkNOSW1HTkVnWWwKR0ZIWjlyd2dDbzJZL2psYWcxdEtjbHBPVFpabS9ZcnRWK0hlYmZqMTN6WFNSdGlIRWFLc0VRc0d5bnY3cENZSwpuY2tTUjFBS2FCbHZFanVjVmxPdHB0MGJjb3VDKzVUV0xublIrT01paENvYitwZmhSeVJLN1prQ3ZWU3loME9ZCkNNVDdMN0l1UXRmc0l2NmtabDgwSU9OUWFXTzJFSWYwdzlBQWRpZjFST2tjME9TTy9FVWhxd1lWeWNQYnA2dkMKZHd5ZzBTMlJvcHkxWHJNS2J4eDNtWlllL0VaQytZNHBjMm81SXg3RjY1S0VuUGpGNldMOXVLd0p6ekptc1VDdApnV0xjTzlXMjlnS29EdDE5RFB6WWozRE1CUzczTk1xTW5DZVZIVy8wWS82NzF5NEtNZHhKWkNaQWRrd1hsQTE1CjExTmlRYlNybVc0ZWpiZFpXWXAyV0crWGMwMmtmNVJYREUvaEV6UGU3SmFhQzVoekd6NmFLMW1MZVAzQjNIMG4KWGpsUFFPa1BMSWd2TzJ1TlNkdjUzTEl5Q3cweE51N1FyM2JqLzg1NkVUbHBpdlp6V0ZHSkhIUGNSZ0wrMU9PNgpPelp0NVhXYWxzaXF5MjRxcktkemdOMGhNdW1ER2VFZWU0aG96SDVjMVhLUFIwaHF3b2ltTUxRa3BrZkQzM1NUCitDVXZhekV0WER0RnJHU3YvV09Dc1Z6dklvTkZJRkxtdGJ4Q2Z6ZTdpMHpOQnJkSHQ3M0Rzb2VuM00wd1R6QnYKYWRQOGxETHpQNE1tUnFKcVlCVmFwa2RVN1pNOW9FWVp0R0VyY0RHc3NBNkUvUGY0bTBLQllJR1NhcVMrU2ZOUAoxaUlYclhiRmVjUWdxMHA4Q054OVRjNTVQZi8yWmt0RHMwMkJ1WVNNZWV3SDk3T2FHWnBhdyttSUk4cHpxRWZKCndXVWM3SmJzUVJudTJyQ2RIcitId1MzNDZNTklTQWRKeExRaFVtVnRiM1JsSUZOcFoyNWxjaUJVWlhOMElEeDAKWlhOMFFIRjFZVzR1ZEc4K2lRSFVCQk1CQ2dBK0ZpRUVtRjlvMzc1TGpDQllLWEl3QlZIMFVxdmtZNlFGQWw4Ngo2dlFDR3dNRkNRUENad0FGQ3drSUJ3SUdGUW9KQ0FzQ0JCWUNBd0VDSGdFQ0Y0QUFDZ2tRQlZIMFVxdmtZNlFqCm53di9RelUxUXEwcTFxZmZ2eTRsNk5tcFFYeUk2QW5JTzVpRzk3U3ZEd3R5eGRrWFZtQ1pNNTJwN1Y0bkMzSVAKVGFLUDRyMk9LSDNEMVVIK1QxMXh3Z3VjRXc2N2FUdGU3bWhrT0R5b0JKNm1OajdiWVpReDVTVlFZTDhkV1E1Sgp2clM0RXJYY2hXM2o5c1l5Sk1xU0hFeml6RVh0dndSVnVuMTlETVdVWWRybTNmbGFHNW81RnZyM094RzgvTjFDCnVMZS9SN0h5aG53QW9QN1ZSUXhBejlMbjZuQmpwRFJLMUFkWjQ3WnNRZmxrUlVsM2JvaDZwTEo0VUtJZzNVSFMKTHdmaWUxTFNCS3RqNzNYK0xwTHZ1T1FIdU5hMTRLcldUaVlBc2RPbVJQaS85bE9nOE8vdDZvT01uZ3pmNFZBWQordGlSZ0NUdElxalBJRjkrRzFyRWRUNm9ZMWo3ZVpoQVh3MG9tOEFINVY0VHVTSVJjRmlrUnlBQVdyWVA4REEwCjE1bEdTYU9SSkFpdDJHVUxVS1Nac3pWMDNtM28wU1I1NWVuZ3ZqUjdDUnVXbVRiWGRIOEViNWxHREpzc1VQQ2kKUHRHSzFZMHY1REtiOGxWMHBNYTNMcVIwWFQ2YlJtZ3RucURNN0ZCMEdFN0F5SXo3MjFpa0VLcWlZM0FYTW1PYgpPbzdnblFXR0JGODY2dlFCREFDL215RWxpVVhlR1A1VFNHVzVFdDRwM0RrQUdLNzZHK280M09reXY1YTh6RXlFCmhYS2FlRXN3R0hxeGFuKzZ3ejBpSXFDRTN4dTU0R2phdWdiOWRuQ0dtcTRmRDJPbHkzbnprdUMwZVZFOGRBMG4KWVZ1S0ZRWlVwS3dpRXE3K1VDTWtuZFNoS1ljVlR2Y1FrNThzZ1FmWllrWHRYam1rbGMvZWVvcEErenBvTG1TbgpZZTlaR3dyelIwWW45cVprUFdaOE9KTnJibXRCOW5zS05kbXhrUDhneldBWXpoNU1HY2QxNUZSUXdwajZYRHFNClJrZFFYdThZbzNacUZRL3paVjREOUtscFEvc3FwcllTR21zMW5tV0lWRXhENXpDUlNVbWlrVVNKdlZlU2xNQWsKTURFdWZKTVNwTlk4eHllbzZ3dTh2TlBwS1VJTmQ4WkJjQVdqeU1rSzhYVVFLdGQyY1RhZlYxSFdGZWFlLzA5TgpraVpzZmp0aEtPVkNNT0laTVdzc1RVaXU3TnViem5iTWVGZ1ZjZXVFNEUxbjlZSGU1UHRJNzZ5YkwwU3FMSU85CjNkdk9EK3lqSG9XcGRDRnEzY0FTN09YejI0SEh0Qll6Uzl3a2oram9KaEZQSlNvN1dEMXU2bC9iSlNtMGc4Z0gKVU5Jb2RIRXBLbzRQcDZCQWVIVUFFUUVBQWY0SEF3SU55RDhOc2lvUTNmOUp1U0JwMTNtWnhUeklWeTltcnJYdgpJR05qaklaN1crcitjdXphZFRNMnFnR1pHUnptSyt4b2VIUG52aHRQRFFUMGhhVzBDL3NWUXQxcUVTQlJUUGtDCnkrSzg2bTQrUWszUmxvREFDYnhMbUVWS3RBZE1uaU1pMGl6amZSU2FoUDhreUx5R0o4aSs5YVVkNlV1ZDNzb2EKVk5ySUlSQjg4b1p4Umhva2FpUmZXOTB0Z2ZSZFAxcW5rVllxajVQZlBRWStPeFJMWStwc2NobEk4bjFJTWFDUwp5cVRyQk8zRXFneVpjMDcvbFFNaDQ4cmdYcUpYakIzclphUnR5b3ZyMXZhUnBrb1dNeE5hOTFjQ2NCbmxVbzcwCmhHT3BtYXIwSS9lZmJzOS9aQkticWk1OE4yNDdCTURtdTJ5a1pjMG1aYUNYeE0vODdWb1lMeGFhc0VuYTRMa04KM21kT2U0eUZWSVFmaGRLdGxTNFZuZWNST2dQT2dHL1V3RjBHZEI1dzFyRkJWRXV0eHFJckpmd3E3Tk5TRXVQaAoyUjdMT0wwa010VlZJazRNc1lpMzRPQWRFQ2MxUnpQaFhPbUpyaVFjTHU1bTBHQVF5OWNZNEttQU03TmhlN3FVCjVGUHFBRkRiVUpYemxBbS9WdDFVWGVWVGs2eHNPV0grQW9NNC9zY2VDWEZMYXlaWVY5OGVYd215RjhzVEdmRy8KRDFUM3oyZUFiaE5QNFEzMUZsMVZWais4L2pHY1RLR0d1TWdsZDk0ZUtjdnA5WUdneTkvQ0I4ODRXbjBWZzlDZApaY3pnb24ySVhvc1ZFVjJOVlBHT1RTVk8waC8vV1lEQkZmVXVKb1B6UERkOHMwSGQxL2hmb2lhN2s5Q0xaSUVICmZPSStZalZvYkR6dkhaVHB2RUxwN2k0QW1rVjJwc3RyV1k3R3RhRHU2d1pVakt6aHQvb3FIRVVUY2wwajRJUDIKQ1hkZytSV3RHd1duM21hVFJEQWMvNUJ0b0dkMVNpajVVcDBZOExJTzhiYUliNlMwS2pwUDdrYjl5NC8wL2NZeAp1WkZRTmlyMlBObktSYnBBa2Nzd053MXFRWFQ5UVJRZFgrNmdid283US9nR3VoK1B4K1lKZnkzbEtxUlNnV2U4Cm93R3ZMakk3UzhMYkdoVVRzQnFLdktxOWRjaXVzY0FYU3J4L24vZ1l2OTlhZTNPeDZXaGlPNjk3WGpRa1lYNVUKUjdUVkpIY1hpbitHazRmcnMwd1NKR3FuSHh2bTk4eUtCQTd5TW52a0NheGRCbi8ydjZXK2VXZWQyL2RWRkI3TQpwT3Nsby9uL0loTEVPSWJ5dkRrK0Z6MUJ6azl3MGUvMDJ1cXV4WFBXYTJaMzBrWVJMdndOOWpmOUhXRHZMb1RFCnk1eExORWxNbDJVNUdsL1FURnVpVyt5NFluODZLdGRjR0VSZHlDQ2xNRjRCRHM0dkhsTGhPUlVDOUxPWHJvSGEKWlpHaGdmOVU0WjJXS2dQSXdrWFNrMHppUStGMWJoWDRuS2VwY3Y1bzRaVVJNaCtCTGhPdWFZaExqSWpHT2RuMwphblVYOHV5RGVYbWs1VUNHbGRVcENRSHFHTHk4amR4ek1pdDJzaEg4WUk2N3R2bEdERnN1M2dwellNVXpXNTIxCjJTM2pxQ1A0dXFta2tCTHNwd0dmOEt0SHBDOTFGTGZUZjBsQ3NpL0hZTUtHUWdFdXIrSlQ4VjV3Y2EyS2dGWUMKVVdVQnE0aWNpRmg1ZGZsZHFMQWRuOVJoMC94b05JQ3FtNnVlSG9rQnZBUVlBUW9BSmhZaEJKaGZhTisrUzR3ZwpXQ2x5TUFWUjlGS3I1R09rQlFKZk91cjBBaHNNQlFrRHdtY0FBQW9KRUFWUjlGS3I1R09rZDA4TUFKTG1wSEhGCjhTRTJrWFJmWTAvM2ltQzBsSG9KajVWUGE3T1pFRlBtOXNrQnpFQ0UzY2luQjRjckNEZGhMR0pFaFNZbmJmbnEKL2F1ZjdkQnRaUytRanVseUdIanhORGZjaXR1OHp4dXExMnBoc3lYWklNZ2pYNUNsMVYxVkdIM3BuVm0vbnVTdgp3WjdVcmV3MXBKNEVwK3h0UlpoY3dRY0NqWVQyOXpQcElVMm9MdDUwTERNZE5tdFVZbW9kMU4yM1RjZDQ5NkdLCmV2Ri9hMDFlWjNVQTc3OWpDdkM4RFMxc1dIMkRUeDdhV1VxaThnV2E0eE9ac0JKbHl5cExaRHBEUEVUcDIvK1cKRmxsV005NnVieUFwdmt3WklPR2dnbndNUVhiSjMybTV2VnhnUWtVWWw5OFZGRXR0a2EzclRRdFArSG5mbnRxagoyTFZsNTRWS1VoQmlHUlBPQzhPcnBBbzVIWS9KazJkWmFmTXRUbGJpUWRnekN3M0xCOW40TWM3VjdkN3JKVDdECldxMUcwOWxBbFFXay8zcjJKbUJiYXlHcDlVbGlwTCtINHI0QU9RaXJ3bXVhSE1KOWJIQ256Z0FVTUhvbXcwTkQKa3RrRG5uUEtaMlR4Y1NEOW00cWdyZjFxRlhrYlFIZ0lvY2w0d2N1cTdaZWdJcjdaN2hZVmQwRWZPQT09Cj1WbWpiCi0tLS0tRU5EIFBHUCBQUklWQVRFIEtFWSBCTE9DSy0tLS0tCg==
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-signer
  namespace: default
spec:
  minReadySeconds: 2
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      quan.to/servicename: remote-signer
  template:
    metadata:
      labels:
        quan.to/servicename: remote-signer
    spec:
      containers:
      - env:
        - name: DATABASE_NAME
          value: remote_signer
        - name: ENABLE_RETHINKDB_SKS
          value: "false"
        - name: KEYS_BASE64_ENCODED
          value: "false"
        - name: KEY_PREFIX
          value: key_
        - name: PRIVATE_KEY_FOLDER
          value: /secrets/
        - name: READONLY_KEYPATH
          value: "true"
        - name: SKS_SERVER
          value: https://keyserver.ubuntu.com
        image: quantocommons/remote-signer:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /tests/ping
            port: 5100
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: remote-signer
        ports:
        - containerPort: 5100
          name: 5100tcp02
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /tests/ping
            port: 5100
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /secrets
          name: remote-signer
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: contaquanto
      restartPolicy: Always
      volumes:
      - name: remote-signer
        secret:
          defaultMode: 256
          optional: false
          secretName: remote-signer
---
apiVersion: v1
kind: Service
metadata:
  name: remote-signer
  namespace: default
spec:
  type: ClusterIP
  selector:
    quan.to/servicename: remote-signer
  ports:
  - name: 5100tcp02
    port: 5100
    protocol: TCP
    targetPort: 5100
  sessionAffinity: None
  type: ClusterIP
