dist: xenial
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - GO111MODULE=on
  - secure: tN/ZizPDjqWLY91QG07XlZraNMMC78Tpru1aEPOXaORC6j7oFVsGHENDFmcl4Cc4F9ATxEeqMTSmQFKAbma55NRDzu17x8EyCAmmk7tj4idVZXvH/B6Ad6hMFPom8NIlkZrb6ReDjxpeOMwrv36oFFZTh4ivhO/pkzAVCxhD9R/ZfD6jY0STRfiGSjwQa/9sXksMh4vgAlMyq10soQdmUX9JKqDvr/+C0zXno4aZtJAno2OYLdAcbmWZibpYQT+mDh6/HpHUqX3oCbS//+lJ8Mq9tJxO5kjRLknPNheD08weno8uIPqsPo+Qt4m3rLrAx9zNKdXf0J1OHx1E6Y47jeXOpd8SJ4F3pV1zx+XlePxQnR645wTF0pMU1drxi6MtLfEos6u0maYCIUbdMkHgoVP/akENJAJBa+U5WuAMKXGI9wKHgCXAk6e76TNAMaKQk8bY8VGgM+tt0B7wZeqpF3VX8JjvI/5amRFjDMLcRmE5BLeccPJO6vWSfYU5RGv8ePPODbnsTSxseGn1TAGdB0nKbErXc9oG26I7njOLrHViS/ld9MqyDsnFOuQ6QiVfsW/xGr/KFSE+LBsTNrMmhJn8aEiv29I/4XV20sKWv4SY5LTE209xS5KS77GFKSR1cHEnce19qmaZEEZRn/kjWB2mWqEMDXqXmHJdO9UKBQQ=
language: go
go:
- 1.13.x
git:
  depth: 1
script:
- echo "Calling travis-binary-build.sh"
- "./scripts/travis-binary-build.sh"
- echo "Done"
deploy:
  provider: releases
  file_glob: true
  file: zips/*
  skip_cleanup: true
  on:
    tags: true
    repo: quan-to/chevron
  api_key:
    secure: Ib/VOdhLDLaUg6CtguRkfy1L5Zrs0y7o0W2z9P3Sxd6KyWnTMdJZqgPBGgwR1ixoFvdaQmtfbyQ0zbZWFigVEts/hzcHmYZsvoRfW6xzMLa46TlDPh0v5xvQ99uOSDiYI9mWOtROPCQym//YZWSu9uzJcRofRtNID7bNwjAEOMiwGENkUP21AgixAc9wKb8mfuIGNWUa+IRRunkqppDkdcmTs+wTdadJAjSnks/4V3nLn2zK1190LS08bOTb3Sj1UhGPgUTTQr8/wESWF2Ni4JYIiy7nItltK3AzHORrQ1MyIQKZkXpdjfuC741kWZX8fHRH+YEY9XK/NPng5tEZXzvOBf7eXZ40gfdaK8E0xWGFm7MbUgK/FN3F098tGcApe97+qIAKyIHevmJMqLNXuN+TI10orPJFeKy5NPZqsMYGuoIW9snVSlGBtSDckaZDysGvKFLiyFSbZyVc05SE9Afx9rJvhr6whERf9Ur8XEcOuGSe6mdrlxSM2/teWU0YjXLLNU5hWVdI+yqXMmd+SdY37XwSNOpzlli3UzkzKSmvqXAMrM6p2m4WkGbXMzxSBCk9yzN9s0ZrgMU5qr1VkrcUTBpoXEiWYQNg3h82XTW/BI3Dg7sUpnptWf5KiRcx7ADTB8mYg0aU29LlcJxIMXCNYVQ2uUB9O9JGqbTnvgE=
